# Generated by Django 3.2.7 on 2021-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
