# Generated by Django 3.2.7 on 2021-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_calculator', '0003_user_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smoker',
            field=models.BooleanField(default=True),
        ),
    ]
